#print("Athmika G pillai","she is my world")
#print(45+22)
#print(988)
#name = input("name : " )
#age = int(input("age : "))
#value = float(input("value : "))
#print("your details is s follows :")
#print("name is ",name," of age  ",age,"worth value of",value)
#if-elif-else
#light = input("enter light : ")
#if(light == "red"):
   # print(" stop vehicle")
#elif(light == "green"):
    #print(" you may go ")
#elif(light == "yellow"):
    #print(" check before u go")
#else:
    #print(" traffic light is not working")

mrk = int(input("enter your mark : "))
if(mrk==100 or mrk>=90):
    print(" A ")
elif(mrk==89 or mrk>=80):
    print(" B ")
elif(mrk==79 or mrk>=70):
    print(" C ")
else:
    print(" D ")












